# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr1=np.arange(10).reshape(2,5)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [6]:
arr1=np.arange(10).reshape(2,5)
arr2=np.ones(10).reshape(2,5)
np.vstack((arr1,arr2))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [7]:
np.hstack((arr1,arr2))

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [10]:
arr1=np.arange(10).reshape(2,5)
arr1=arr1.reshape(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [21]:
arr1=np.arange(15).reshape(1,5,3)
arr1=arr1.reshape(15)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [25]:
arr1=np.arange(15)
print(arr1.reshape(5,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [29]:
arr=np.arange(25).reshape(5,5)
arr=arr*arr
print(arr)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [40]:
arrmean=np.random.randn(30).reshape(5,6)
arr=np.mean(arr)
print(arr)

0.21168466830087654


## Question:9

### Find the standard deviation of the previous array in Q8?

In [41]:
np.std(arrmean)

0.9579214962896797

## Question:10

### Find the median of the previous array in Q8?

In [42]:
np.median(arrmean)

0.24452517631357906

## Question:11

### Find the transpose of the previous array in Q8?

In [43]:
np.transpose(arrmean)

array([[ 0.48302123,  0.16335139, -0.37708613,  1.74127281, -1.23462316],
       [ 0.5381186 ,  0.21011548,  1.61819917, -0.66333921,  0.22680816],
       [ 0.43811988, -0.0101571 ,  0.42571638,  0.49260204, -2.29377054],
       [ 1.09870496,  0.31461416,  0.91055365, -1.02533275,  0.2622422 ],
       [ 0.55966989, -1.12835474,  1.22283237, -0.45659713, -1.56135415],
       [ 1.61484848, -0.26720914, -0.80878267, -0.19077096,  1.13581406]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [51]:
diagsum = np.random.randn(16).reshape(4,4)

print(diagsum,'\n\n','Sum= ', np.trace(diagsum))

[[ 1.48461576 -1.7972221   1.44375136 -0.63344906]
 [ 0.91494408 -0.05267989 -1.17259691 -0.65036287]
 [-2.0942323  -0.68794685  0.06379294  0.3145448 ]
 [ 0.24259197  0.4935879   0.44315322 -0.15530856]] 

 Sum=  1.340420245155769


## Question:13

### Find the determinant of the previous array in Q12?

In [52]:
np.linalg.det(diagsum)

2.820437212420328

## Question:14

### Find the 5th and 95th percentile of an array?

In [55]:
p1 = np.percentile(diagsum, 5)
p95 = np.percentile(diagsum,95)
print(p1,'\n',p95)

-1.8714746477931001 
 1.4539674624837644


## Question:15

### How to find if a given array has any null values?

In [58]:
arrsum = np.sum(diagsum)
arraynan = np.isnan(arrsum)
print(arraynan)

False
