# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [10]:
x=np.empty(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [7]:
y=np.arange(10,49)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [8]:
np.shape(y)

(39,)

5. Print the type of the previous array in question 3

In [12]:
y.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [13]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [14]:
y.ndim

1

8. Create a boolean array with all the True values

In [19]:
z=np.ones(10, dtype=bool)
print(z)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [26]:
arr2d = np.array([[2,3],[3,4]])
print(arr2d)

[[2 3]
 [3 4]]


10. Create a three dimensional array



In [28]:
arr3d = np.array([[2,3],[3,4],[4,5]])
print(arr3d)

[[2 3]
 [3 4]
 [4 5]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [30]:
vec = np.array([1,2,3,4,5,6,7,8,9])
print(vec[::-1])

[9 8 7 6 5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [33]:
nulvec = np.zeros(10)
nulvec[4]=1
print(nulvec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [34]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [37]:
arr = np.array([1, 2, 3, 4, 5])
arrfloat = np.array(arr, dtype=float)
print(arrfloat)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [41]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
print(arr1*arr2)


[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [42]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

comparison = arr1 == arr2 
equal_arrays = comparison.all() 
  
print(equal_arrays) 

False


17. Extract all odd numbers from arr with values(0-9)

In [51]:
arr=np.arange(0,9)
odd=arr[1:9:2]
print(odd)   

[1 3 5 7]


18. Replace all odd numbers to -1 from previous array

In [54]:
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [58]:
arr = np.arange(10)
arr[5:9]=12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [59]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [60]:
arr2d = np.array([[1, 2, 3],
            [4, 5, 6], 
            [7, 8, 9]])
arr2d[1,1]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [78]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[:,0,:]=64
print(arr3d.shape)
print(arr3d)

(2, 2, 3)
[[[64 64 64]
  [ 4  5  6]]

 [[64 64 64]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [89]:
arr2d = np.arange(0,9).reshape(3,3)
print(arr2d[0,:])

[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [90]:
arr2d = np.arange(0,9).reshape(3,3)
print(arr2d[1,1])

4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [92]:
arr2d = np.arange(0,9).reshape(3,3)
print(arr2d[0:2,2])

[2 5]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [100]:
ten = np.random.randn(10,10)
print(ten)
print(ten.min())
print(ten.max())

[[ 0.08154986  0.85411622  0.00735395  1.32829103  0.98256892 -0.57707984
   0.82729132  0.59524918 -0.19194252  0.66861751]
 [-0.53486434 -0.77921749  1.67503115  1.64188353  0.01740825 -0.16315517
  -0.25525364  0.42708355 -0.26306635 -1.05480413]
 [ 0.47489373 -1.76596567 -0.0854713  -0.57553312  0.9381097  -1.63454067
  -0.32482932 -0.75298967  0.92440025  1.3838616 ]
 [ 0.36206367  1.04817572  1.06607619 -0.18021203  0.52435591 -0.04766464
  -0.64766937  0.72609885 -2.02130391  0.53969152]
 [ 0.65967798  0.84112764 -0.5774344  -0.02959521 -0.40935615  0.08836728
  -0.5650183  -0.10467675  0.56243632  0.33651102]
 [ 1.05252568 -1.14043049  0.79963894  0.7071523   1.6376064  -0.77433986
   0.49670917 -0.1016047  -0.97953499  0.72340217]
 [ 1.58690436  1.48664194 -1.49687704  0.26096318 -0.16184239  0.06103368
  -0.29667401 -1.16338035 -0.42413967  0.32353166]
 [ 1.15873829 -0.04508269  1.03228398  3.08717276  1.09608235 -0.32193481
  -0.89070413 -0.87104242  0.17217171  0.62953036]


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [103]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [105]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [111]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[names=='Will'])

[[ 0.71887831 -0.34717453 -0.3185404   0.6863039 ]
 [ 0.26520269 -0.11883464 -0.10466357  0.4514345 ]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [119]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[(names!='Will') & (names!='Joe')])

[[-1.06492791  1.80208445  0.73401544  0.38047747]
 [ 0.81772453  0.97944106 -0.77512148  0.76775406]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [121]:
x=np.random.randint(1,15,(5,3))
print(x)

[[13  8  5]
 [ 3  2 12]
 [13  8 10]
 [ 2  5 13]
 [14  3 13]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [122]:
x=np.random.randint(1,16,(2,2,4))
print(x)

[[[ 6  6  9  5]
  [10 13  6 14]]

 [[12 15 11 15]
  [ 9  6 15  6]]]


33. Swap axes of the array you created in Question 32

In [123]:
x.transpose()

array([[[ 6, 12],
        [10,  9]],

       [[ 6, 15],
        [13,  6]],

       [[ 9, 11],
        [ 6, 15]],

       [[ 5, 15],
        [14,  6]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [137]:
y=np.random.rand(10)
ysqrt=np.sqrt(y)
ysqrt[ysqrt<0.5] = 0
print(ysqrt)

[0.92173574 0.87288782 0.88886416 0.         0.633364   0.53172509
 0.70428855 0.         0.         0.67174477]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [142]:
a=np.random.rand(12)
b=np.random.rand(12)
print(np.maximum(a,b))

[0.31895806 0.48962491 0.56767072 0.72189379 0.46992389 0.50750473
 0.78168975 0.86891511 0.37270071 0.95347363 0.81464502 0.92916914]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [145]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [154]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a, b))

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [172]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:,1:2]=newColumn.reshape(3,1)
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [175]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x,y,np.dot(x,y))

[[1. 2. 3.]
 [4. 5. 6.]] [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]] [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [180]:
x=np.random.randn(20)
print(x)
print(np.cumsum(x))

[-0.85470856 -0.36508294  1.01336315 -0.36217023 -0.15747454 -1.57625903
 -1.15423109  1.13564921  0.81301865 -1.23219861 -0.13332905 -0.79568559
  0.90060944 -0.58626409 -0.08422788  0.68741943  0.22823991  0.35545179
  0.04735006  1.45084254]
[-0.85470856 -1.21979149 -0.20642834 -0.56859857 -0.72607312 -2.30233214
 -3.45656323 -2.32091402 -1.50789537 -2.74009399 -2.87342303 -3.66910862
 -2.76849918 -3.35476328 -3.43899115 -2.75157172 -2.52333182 -2.16788003
 -2.12052997 -0.66968743]
